// Auto-generated by contracts/scripts/lib/exportAbi.ts — do not edit by hand.
export interface DeploymentContracts {
  NVIDToken: `0x${string}`;
  FeeCollector: `0x${string}`;
  RewardVault: `0x${string}`;
  Treasury: `0x${string}`;
}

export interface Deployment {
  network: string;
  chainId: number;
  deployer: `0x${string}`;
  owner: `0x${string}`;
  nvdaToken: `0x${string}`;
  timestamp: string;
  contracts: DeploymentContracts;
}

/** Keyed by chain id. Written by `contracts/scripts/deploy.ts`. */
export const deployments: Record<string, Deployment> = {};
