import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

/** Contracts whose ABI the frontend consumes, with the identifier the frontend imports. */
export const EXPORTED_CONTRACTS = [
  { name: "NVIDToken", exportName: "nvidTokenAbi" },
  { name: "FeeCollector", exportName: "feeCollectorAbi" },
  { name: "RewardVault", exportName: "rewardVaultAbi" },
  { name: "Treasury", exportName: "treasuryAbi" },
] as const;

const HEADER = "// Auto-generated by contracts/scripts/lib/exportAbi.ts — do not edit by hand.\n";

export function frontendAbiDir(hre: HardhatRuntimeEnvironment): string {
  return process.env.FRONTEND_ABI_DIR
    ? path.resolve(hre.config.paths.root, process.env.FRONTEND_ABI_DIR)
    : path.resolve(hre.config.paths.root, "..", "frontend", "lib", "abi");
}

export function deploymentsDir(hre: HardhatRuntimeEnvironment): string {
  return path.resolve(hre.config.paths.root, "deployments");
}

/**
 * Writes one `<Name>.ts` per contract (ABI as a `const` array so wagmi/viem
 * infer types), an `index.ts`, and `deployments.ts` built from every
 * `deployments/<network>.json` on disk.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  const outDir = frontendAbiDir(hre);
  fs.mkdirSync(outDir, { recursive: true });

  const exportsList: string[] = [];
  for (const { name, exportName } of EXPORTED_CONTRACTS) {
    const artifact = await hre.artifacts.readArtifact(name);
    const body = `${HEADER}export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
    fs.writeFileSync(path.join(outDir, `${name}.ts`), body);
    exportsList.push(`export { ${exportName} } from "./${name}";`);
  }

  exportsList.push(`export { deployments } from "./deployments";`);
  exportsList.push(`export type { Deployment, DeploymentContracts } from "./deployments";`);
  fs.writeFileSync(path.join(outDir, "index.ts"), `${HEADER}${exportsList.join("\n")}\n`);

  writeDeploymentsModule(hre, outDir);

  // eslint-disable-next-line no-console
  console.log(`ABIs exported to ${path.relative(process.cwd(), outDir) || "."}`);
}

export interface DeploymentRecord {
  network: string;
  chainId: number;
  deployer: string;
  owner: string;
  nvdaToken: string;
  timestamp: string;
  contracts: {
    NVIDToken: string;
    FeeCollector: string;
    RewardVault: string;
    Treasury: string;
  };
}

function writeDeploymentsModule(hre: HardhatRuntimeEnvironment, outDir: string): void {
  const dir = deploymentsDir(hre);
  const records: Record<string, DeploymentRecord> = {};

  if (fs.existsSync(dir)) {
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith(".json")) continue;
      const record = JSON.parse(fs.readFileSync(path.join(dir, file), "utf8")) as DeploymentRecord;
      records[String(record.chainId)] = record;
    }
  }

  const body = `${HEADER}export interface DeploymentContracts {
  NVIDToken: \`0x\${string}\`;
  FeeCollector: \`0x\${string}\`;
  RewardVault: \`0x\${string}\`;
  Treasury: \`0x\${string}\`;
}

export interface Deployment {
  network: string;
  chainId: number;
  deployer: \`0x\${string}\`;
  owner: \`0x\${string}\`;
  nvdaToken: \`0x\${string}\`;
  timestamp: string;
  contracts: DeploymentContracts;
}

/** Keyed by chain id. Written by \`contracts/scripts/deploy.ts\`. */
export const deployments: Record<string, Deployment> = ${JSON.stringify(records, null, 2)};
`;
  fs.writeFileSync(path.join(outDir, "deployments.ts"), body);
}
